# Welcome to Jekyll!
#

# Site settings
title: Stan Liu
description: Become a Swifter. Love Coding.
owner: Stan Liu # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: lyc2345@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.com/lyc2345/lyc2345.github.io" # the base hostname & protocol for your site
project:
  lyricism: https://github.com/lyc2345/Lyricism
  alert: https://github.com/lyc2345/Alert
social:
  twitter: https://twitter.com/stitchyQQ
  github: https://github.com/lyc2345
  linkedin-square: https://tw.linkedin.com/in/stan-liu-269093bb
  facebook-official: https://facebook.com/lyc2345
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

collections:
  pages:
    output: true
